### ISSUE TITLE
implement machine learning algorithms for prediction 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#109]
implement machine learning algorithms for prediction

**Comment by gwenchee** [comment]
types 
- arima 
- seq2seq

**Comment by gwenchee** [comment]
arima is implemented: https://github.com/ergs/d3ploy/pull/122/files

**Comment by katyhuff** [comment]
for seq2seq : won't fix, but @FlanFlanagan , can you please add comments here, in this issue describing why not for posterity?

**Comment by FlanFlanagan** [comment]
Sequence to sequence relies on giving the algorithm a sequence as a target. This doesn't make sense for use because if we know the target sequence there is not reason to run d3ploy. I'm going to close this because I don't think seq2seq is right for us. 

I'm happy to re-investigate the issue if need be.
