### ISSUE TITLE
tech pref has a one time step lag 

### ISSUE THREAD

**Issue by gwenchee** [arfc/d3ploy#133]
tech pref has a one time step lag with the change of tech preference.

**Comment by gwenchee** [comment]
This can be seen in https://github.com/ergs/d3ploy/pull/135 in `test_tech_pref_cross`. At time step 6m the preference for reactor 2 is larger than reactor 1, yet reactor 2 is not deployed

**Comment by jbae11** [comment]
so the time progression of the preferences are as follows:
```
1
{'reactor1': 10, 'reactor2': 1}
2
{'reactor1': 9, 'reactor2': 2}
4
{'reactor1': 7, 'reactor2': 4}
5
{'reactor1': 6, 'reactor2': 5}
6
{'reactor1': 5, 'reactor2': 6}
7
{'reactor1': 4, 'reactor2': 7}
8
{'reactor1': 3, 'reactor2': 8}
9
{'reactor1': 2, 'reactor2': 9}
```
so at timestep 6, it will *schedule build* of reactor2, meaning that reactor2 will enter
at timestep 7, since the timestep execution of cyclus is:
`build -> tick -> DRE -> tock -> decom -> decision`
so it should have a one time lag

If I understand it correctly.

**Comment by gwenchee** [comment]
Ah I see, that makes sense , so I Guess this isn’t an issue then!

**Comment by jbae11** [comment]
welp but maybe the test assert needs to be changed?

**Comment by gwenchee** [comment]
Ya you are right, just gotta change 6 —> 7 for the cross test.
