### ISSUE TITLE
capacity vs demand

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#142]
I think there needs to be a distinction between capacity and demand.

For example, the sink currently 'demands' waste, which might trigger large number of deployment. It instead should 'supply' capacity.

**Comment by katyhuff** [comment]
We have frequently discussed this in the context of Cyclus in general (there may even be a CEP). You have the right idea. The traded object still needs to be the waste though.

**Comment by FlanFlanagan** [comment]
Ah yes. 

The sink was giving a demand because my initial thought was for d3ploy to handle the reversal. Basically setting up d3ploy to have two commodity streams. One would be how it works now, the other reversing the flow by allowing a demand to be framed as a supply. 

I did this because I thought it would be better for archetype developers to follow a 'I'm asking for this commodity, therefore it is a demand' thought. However, I'm open to changing it.  I don't actually see a reason the sink would demand something, but it's possible another type of facility might serve a similar sink function but actual demand something...like heat maybe?

**Comment by jbae11** [comment]
In the ddca call we decided to have a `reverse commodity` where the supply would drive deployment of the demand, instead of demand driving supply facility. For example, the sink would demand `waste` (as it is now). If the supply of waste is larger than demand, d3ploy will deploy a sink facility. This way, the Cycamore archetype records would remain intuitive (sink is demanding waste in DRE).

**Comment by gwenchee** [comment]
closed with https://github.com/ergs/d3ploy/pull/144
