### ISSUE TITLE
self.commodity_demand[commod] is a dictionary, but can be an array

### ISSUE THREAD

**Issue by jbae11** [arfc/d3ploy#52]
currently, the variable `self.commodity_demand[commod]` (also `self.commodity_supply[commod]`) is a dictionary with:
* key: time (integer)
* value: supply or demand quantity

I personally think that this would be better if it was a numpy array. This would eliminate the need for [this line](https://github.com/ergs/d3ploy/blob/correct-develop/d3ploy/no_inst.py#L247) because the arrays could be initialized as zeros in the beginning. 

What do you think @FlanFlanagan ?

**Comment by FlanFlanagan** [comment]
I disagree. I'd rather keep the system the way it is. It provides the ability for the system to track only certain time steps if that because important later on, and provides additional data to the system. 

That line does not take up much computation, not sure why you need it removed? Is this system causing a systematic error in the code?

**Comment by gwenchee** [comment]
We decided that we will stick with the dictionaries? Should we close this? @jbae11
